image: ubuntu:20.04

stages:
  - build_llvm
  - build_tests
  - test

build_llvm:
  stage: build_llvm
  timeout: 3h 30m
  variables:
    CC: clang
    CCX: clang++
    DEBIAN_FRONTEND: noninteractive
    TZ: Europe/Paris
  before_script:
    - apt update -y && apt install -y ninja-build lld clang cmake perl
  script:
    - mkdir build && cd build
    - cmake ../llvm -DLLVM_ENABLE_PROJECTS="clang;openmp" -DCMAKE_BUILD_TYPE=MinSizeRel -G "Ninja" -DLLVM_ENABLE_LLD=ON -DLLVM_PARALLEL_LINK_JOBS=8 -DLIBOMP_TASKGRAPH=1 -DLLVM_LINK_LLVM_DYLIB=ON -DLLVM_BUILD_LLVM_DYLIB=ON -DOPENMP_ENABLE_LIBOMPTARGET=OFF
    - ninja install
    
build_tests:
  stage: build_tests
  timeout: 1h
  variables:
    CC: /bin/clang
    CCX: /bin/clang++
    GTEST_ROOT: /usr/src/googletest/googletest
  before_script:
    - apt update -y && apt install -y googletest git
    - cd /usr/src/googletest/googletest
    - cmake .
    - make
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.bsc.es/ppc/benchmarks/llvm_ompss_tests
    - cd llvm-ompss-tests
    - git checkout master
  script:
    - cd llvm-ompss-tests
    - sh compileEverything.sh
  dependencies:
  - build_llvm

test:
  stage: test
  script:
    - cd tests
    - sh testEverythin.sh > results.txt
  artifacts:
    paths:
      - results.txt
  dependencies:
    - build_tests
  