stages:
  - build
  - test

build:
  stage: build
  variables:
    CC: clang
    CCX: clang++
  before_script:
    - apt update && apt -y install ninja-build ldd clang
  script:
    - mkdir build
    - cd build
    - cmake -DLLVM_ENABLE_PROJECTS="clang;openmp" -DCMAKE_BUILD_TYPE=MinSizeRel -G "Ninja" -DCMAKE_INSTALL_PREFIX=opt/ampere/llvm -DLLVM_ENABLE_LLD=ON -DLLVM_PARALLEL_LINK_JOBS=8 -DLIBOMP_TASKGRAPH=1 -DLLVM_LINK_LLVM_DYLIB=ON -DLLVM_BUILD_LLVM_DYLIB=ON ../llvm
    - ninja install
  artifacts:
    paths:
      - install/bin/clang

# run tests using the binary built before
test:
  stage: test
  script:
    - echo "Do some testing"
